import SectionBesties from '@/components/SectionBesties'
import SectionHero from '@/components/SectionHero'
import SectionBackground from '@/components/SectionBackground'
import Head from 'next/head'

export default function SandBox() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='SandBox'>
        <SectionHero />
        <SectionBesties />
        <SectionBackground />
      </main>
    </>
  )
}
